
data_type_mappings = {
    'integer': 'INT',
    'bigint': 'BIGINT',
    'smallint': 'SMALLINT',
    'numeric': 'NUMERIC',
    'real': 'REAL',
    'double precision': 'DOUBLE PRECISION',
    'boolean': 'BOOLEAN',
    'character varying': 'VARCHAR',
    'character': 'CHAR',
    'text': 'TEXT',
    'date': 'DATE',
    'time without time zone': 'TIME',
    'time with time zone': 'TIME WITH TIME ZONE',
    'timestamp without time zone': 'TIMESTAMP',
    'timestamp with time zone': 'TIMESTAMP WITH TIME ZONE',
    'bytea' : 'BYTEA',
    'geometry_types' : {
        'GEOMETRY' : "GEOMETRY",
        'geometry' : "GEOMETRY",
        'Geometry' : "GEOMETRY",
        'POINT' : "Point",
        'point' : "Point",
        'Point' : "Point",
        'LINESTRING' : "LineString",
        'linestring' : "LineString",
        'Linestring' : "LineString",
        'POLYGON' : "Polygon", 
        'polygon' : "Polygon", 
        'Polygon' : "Polygon", 
        'MULTIPOINT' : "MultiPoint",
        'multipoint' : "MultiPoint",
        'Multipoint' : "MultiPoint",
        'MultiPoint' : "MultiPoint",  
        'MULTILINESTRING' : "MultiLineString",
        'multilinestring' : "MultiLineString",
        'Multilinestring' : "MultiLineString",
        'MultiLinestring' : "MultiLineString",
        'MULTIPOLYGON' : "MultiPolygon",  
        'multipolygon' : "MultiPolygon", 
        'Multipolygon' : "MultiPolygon",   
        'MultiPolygon' : "MultiPolygon",   
    }
}

data_type_mappings_esri = {
    'INT' : 'LONG',
    'BIGINT' : "FLOAT",
    'SMALLINT' : 'SHORT',
    'NUMERIC' : 'DOUBLE',
    'REAL' : 'DOUBLE',
    'DOUBLE PRECISION' : 'DOUBLE',
    'BOOLEAN' : 'TEXT',
    'VARCHAR' : 'TEXT',
    'CHAR' : 'TEXT',
    'TEXT' : 'TEXT',
    'DATE' : 'DATE',
    'TIME' : 'DATE',
    'TIME WITH TIME ZONE' : 'DATE',
    'TIMESTAMP' : 'DATE',
    'TIMESTAMP WITH TIME ZONE' : 'DATE',
    'BYTEA' : 'BLOB',
    'geometry_types' : {
        'GEOMETRY' : "GEOMETRY",
        'geometry' : "GEOMETRY",
        'Geometry' : "GEOMETRY",
        'POINT' : "POINT",
        'point' : "POINT",
        'Point' : "POINT",
        'LINESTRING' : "POLYLINE",
        'linestring' : "POLYLINE",
        'Linestring' : "POLYLINE",
        'POLYGON' : "POLYGON", 
        'polygon' : "POLYGON",
        'Polygon' : "POLYGON", 
        'MULTIPOINT' : "MULTIPOINT",
        'multipoint' : "MULTIPOINT", 
        'Multipoint' : "MULTIPOINT",
        'MultiPoint' : "MULTIPOINT", 
        'MULTILINESTRING' : "POLYLINE",
        'multilinestring' : "POLYLINE",
        'Multilinestring' : "POLYLINE",
        'MultiLinestring' : "POLYLINE",
        'MULTIPOLYGON' : "POLYGON",  
        'multipolygon' : "POLYGON",
        'Multipolygon' : "POLYGON", 
        'MultiPolygon' : "POLYGON",    
    }
}

extra_tables = [
    "gdb_items",
    "gdb_itemrelationships",
    "geography_columns", 
    "geometry_columns", 
    "us_lex",
    "us_gaz",
    "us_rules",
    "pointcloud_formats",
    "pointcloud_columns",
    "sde_coordinate_systems",
    "sde_raster_columns",
    "sde_geometry_columns",
    "sde_layers",
    "sde_version",
    "sde_metadata",
    "sde_versions",
    "sde_states",
    "sde_table_registry",
    "sde_mvtables_modified",
    "sde_state_lineages",
    "sde_locators",
    "sde_layer_stats",
    "sde_xml_indexes",
    "sde_xml_index_tags",
    "sde_xml_columns",
    "sde_column_registry",
    "sde_archives",
    "sde_branch_tables_modified",
    "sde_branches",
    "sde_multibranch_tables",
    "sde_object_ids",
    "sde_process_information",
    "sde_layer_locks",
    "sde_state_locks",
    "sde_table_locks",
    "sde_object_locks",
    "sde_tables_modified",
    "sde_lineages_modified",
    "sde_logfile_pool",
    "sde_dbtune",
    "sde_server_config",
    "gdb_itemtypes",
    "sde_spatial_references",
    'st_spatial_references', 
    'st_geometry_columns', 
    'sde_version_history', 
    'sde_tables_last_edit_time', 
    "gdb_itemrelationshiptypes",
    'dbtune', 
    "gdb_locks",
    "gdb_conflicts",
    'gdb_tables_last_modified', 
    'gdb_replicalog',
    "pg_buffercache",
    "pg_stat_statements",
    "spatial_ref_sys",
    "sde_tables_last_edit_time",
    "sde_archives",
    "sde_branch_tables_modified",
    "sde_branches",
    "sde_column_registry",
    "sde_coordinate_systems",
    "sde_dbtune",
    "sde_geometry_columns",
    "sde_layer_locks",
    "sde_layer_stats",
    "sde_layers",
    "sde_lineages_modified",
    "sde_locators",
    "sde_logfile_pool",
    "sde_metadata",
    "sde_multibranch_tables",
    "sde_mvtables_modified",
    "sde_object_ids",
    "sde_object_locks",
    "sde_process_information",
    "sde_raster_columns",
    "sde_server_config",
    "sde_state_lineages",
    "sde_state_locks",
    "sde_states",
    "sde_table_locks",
    "sde_table_registry",
    "sde_tables_last_edit_time",
    "sde_tables_modified",
    "sde_version",
    "sde_version_history",
    "sde_versions",
    "sde_xml_columns",
    "sde_xml_index_tags",
    "sde_xml_indexes",
    "st_geometry_columns",
    "st_spatial_references"
]
extra_tables.extend([ "i"+str(i) for i in range(1, 750) ])